### ISSUE TITLE
打包后，启动APP就闪退了

### ISSUE THREAD

**Issue by deboLing** [nnnggel/baidu_face_plugin#2]
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165] No pending exception expected: java.lang.NoSuchMethodError: no static method "Lcom/baidu/idl/license/AndroidLicenser;.get_device_id(Landroid/content/Context;)Ljava/lang/String;"
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165]   at int com.baidu.idl.license.AndroidLicenser.init_with_algorithm(android.content.Context, java.lang.String, java.lang.String, int) (:-2)
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165]   at int com.baidu.idl.license.AndroidLicenser.a(android.content.Context, java.lang.String, java.lang.String, int) (:-1)
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165]   at void com.baidu.idl.facesdk.FaceSDK$a.run() (:-1)
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165]   at void java.lang.Thread.run() (Thread.java:764)
2020-08-16 16:57:18.974 3379-3431/? A/m.thunder.trad: thread.cc:2165] 
    
    --------- beginning of crash
2020-08-16 16:57:18.974 3379-3379/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thunder.trade, PID: 3379
    java.lang.NoSuchFieldError: no "J" field "index" in class "Lcom/baidu/idl/facesdk/FaceTracker;" or its superclasses
        at com.baidu.idl.facesdk.FaceTracker.create(Native Method)
        at com.baidu.idl.facesdk.FaceTracker.<init>(Unknown Source:12)
        at c.a.b.a.a.c.a(Unknown Source:8)
        at com.thunder.trade.MainApplication.a(Unknown Source:8)
        at com.thunder.trade.MainApplication.onCreate(Unknown Source:3)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by nnnggel** [comment]
打包会使用混淆，百度的代码混淆会有问题，所以需要在proguard中排除百度的代码
